-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQggqxnby/Q30Z9Wqh0
A7XiqWOrBYpjx1OvCnoc9EDHwmGgCgYIKoZIzj0DAQehRANCAASDGFAAdVNsL0Jh
M4cITJGndQuK23ksgrGfVHvqESJA1XFrJTkQ81AL0JsvJw8BbgBrxUinV8+YREaQ
f9wL8c9T
-----END PRIVATE KEY-----